// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDA065XG19Wf6rp1eW5UOdBl4YCpnfMegc',
    appId: '1:650985879545:web:20f89afd3c2940e740af28',
    messagingSenderId: '650985879545',
    projectId: 'messager-4abd8',
    authDomain: 'messager-4abd8.firebaseapp.com',
    databaseURL: 'https://messager-4abd8.firebaseio.com',
    storageBucket: 'messager-4abd8.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCySk7dqAogmnyArvVDZiNpSz92P3fpG9E',
    appId: '1:650985879545:android:9657b16229a8109c40af28',
    messagingSenderId: '650985879545',
    projectId: 'messager-4abd8',
    databaseURL: 'https://messager-4abd8.firebaseio.com',
    storageBucket: 'messager-4abd8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCdWSxcJgCsdOL2jeGXHyYqj8EpxgxokEM',
    appId: '1:650985879545:ios:dffac0f99ae3178840af28',
    messagingSenderId: '650985879545',
    projectId: 'messager-4abd8',
    databaseURL: 'https://messager-4abd8.firebaseio.com',
    storageBucket: 'messager-4abd8.appspot.com',
    iosClientId: '650985879545-pj6lm1308m44ml5i5liri3n22tmln260.apps.googleusercontent.com',
    iosBundleId: 'com.example.learningApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCdWSxcJgCsdOL2jeGXHyYqj8EpxgxokEM',
    appId: '1:650985879545:ios:dffac0f99ae3178840af28',
    messagingSenderId: '650985879545',
    projectId: 'messager-4abd8',
    databaseURL: 'https://messager-4abd8.firebaseio.com',
    storageBucket: 'messager-4abd8.appspot.com',
    iosClientId: '650985879545-pj6lm1308m44ml5i5liri3n22tmln260.apps.googleusercontent.com',
    iosBundleId: 'com.example.learningApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAInIx5l_W0vBjfbmgDKUmnPLuVsctCHhY',
    appId: '1:650985879545:web:7e1f9a1410e0782f40af28',
    messagingSenderId: '650985879545',
    projectId: 'messager-4abd8',
    authDomain: 'messager-4abd8.firebaseapp.com',
    databaseURL: 'https://messager-4abd8.firebaseio.com',
    storageBucket: 'messager-4abd8.appspot.com',
  );
}
